name: CI/CD

# Controls when the workflow will run
on:
  # Activates the workflow; then there is a push to the main or master branch
  push:
    branches: [main, master]

  # allows you to manually execute this pipeline from the Actions tab.
  workflow_dispatch:

# A workflow run consists of one or more jobs that can be executed either sequentially or concurrently.
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    #
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v2  

      - name: Set up Python
      - uses: actions/setup-python@v2  

      - name: Set up Docker
      - uses: actions/setup-docker@v2

      - name: Install the app's required dependencies
      - run: pip install -r requirements.txt

      - name: Run the test suite
      - run:  python -m pytest

      # - name: Build Docker Image
      # - run: docker build -t my-python-app .
        
      - name: Build Docker Image
          uses: 'docker'
          image: 'Dockerfile'
      
      

      
